services:
  dcts-livekit:
    image: livekit/livekit-server:latest 
    
    env_file:
      - config.env
    environment:
      - LIVEKIT_YAML_PATH=${LIVEKIT_YAML_PATH:-/etc/livekit.yaml}
      - APP_URL=${APP_URL:-app.example.com}
      - LIVEKIT_URL=${LIVEKIT_URL:-livekit.example.com}
    entrypoint: sh -c "/initialize.sh"
    volumes:
      - ./config.env:/config.env
      - ./startup-files/initialize.sh:/initialize.sh
      - ./livekit.yaml:/etc/livekit.yaml
    ports:
      - 7880:7880
      - 7881:7881
      - 7882:7882/udp
      - 3478:3478/udp
      - 5349:5349/tcp
    restart: unless-stopped

  dcts-app:
    build: ./
    depends_on:
      dcts-mariadb:
        condition: service_healthy
      dcts-redis:
        condition: service_healthy
      dcts-livekit:
        condition: service_started
    env_file:
      - config.env
    environment:
      - LIVEKIT_YAML_PATH=${LIVEKIT_YAML_PATH:-/etc/livekit.yaml}
      - APP_URL=${APP_URL:-app.example.com}
      - DB_HOST=${DB_HOST:-dcts-mariadb}
      - DB_USER=${DB_USER:-dcts}
      - DB_PASS=${DB_PASS:-dcts}
      - DB_NAME=${DB_NAME:-dcts}
      - DEBUG=${DEBUG:-false}
    ports:
      - 2052:2052
    restart: unless-stopped
    volumes:
      - ./dcts/sv:/app/sv
      - ./dcts/configs:/app/configs
      - ./dcts/uploads:/app/public/uploads
      - ./dcts/emojis:/app/public/emojis
      - ./dcts/plugins:/app/plugins
      - ./dcts/public/css/themes:/app/themes 
      - ./livekit.yaml:/etc/livekit.yaml

  dcts-mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_DATABASE=${DB_NAME:-dcts}
      - MARIADB_USER=${MARIADB_USER:-dcts}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-dcts}
    volumes:
      - dcts-mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  dcts-redis:
    image: redis:alpine
    volumes:
      - dcts-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


#  caddy:
#    image: caddy:2
#    env_file:
#      - config.env
#    restart: unless-stopped
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./Private_Certs:/etc/caddy/certs:ro # Mount the certs directory as read-only
#      - caddy_data:/data
#      - caddy_config:/config
#    depends_on:
#      - dcts-livekit

volumes:
  dcts-mariadb-data:
  dcts-redis-data:
  caddy_data:
  caddy_config:

