# ---------------------------
# Dockerfile for DCTS Shipping (Bun)
# ---------------------------

FROM oven/bun:1-slim

RUN useradd -m -d /home/container container

ENV USER=container HOME=/home/container
WORKDIR /home/container

WORKDIR /home/container

COPY package.json bun.lock ./

RUN mkdir sv && \
  mkdir configs && \
  mkdir public && \
  mkdir public/emojis && \
  mkdir public/uploads && \
  mkdir plugins && \
  mkdir themes && \
  bun install

COPY . .

EXPOSE 2052