services:
  dcts-app:
    #For local development
    #build:
    #  context: ../
    #  dockerfile: ./Docker/Dockerfile
    image: ${DCTS_IMAGE:-ghcr.io/hackthedev/dcts-shipping:latest}
    environment:
      - DEBUG=${DEBUG:-false}
    ports:
      - 2052:2052
      - 5000:5000
      - 7880:7880
      - 7881:7881
      - 7882:7882/udp
      - 3478:3478/udp
      - 5349:5349/tcp
    restart: unless-stopped
    volumes:
      - ../dcts/configs:/app/configs
      - ../dcts/uploads:/app/public/uploads
      - ../dcts/emojis:/app/public/emojis
      - ../dcts/plugins:/app/plugins
      - ../dcts/public/css/themes:/app/themes 
      - ../livekit:/app/livekit

